from __future__ import annotations

ACTION_ORCHESTRATOR_STARTED = "orchestrator_started"
ACTION_ORCHESTRATOR_STOPPED = "orchestrator_stopped"
ACTION_DAILY_REPORT_COMPLETED = "daily_report_completed"
ACTION_DAILY_REPORT_FAILED = "daily_report_failed"
ACTION_WEEKLY_BRIEF_COMPLETED = "weekly_brief_completed"
ACTION_WEEKLY_DEBRIEF_COMPLETED = "weekly_debrief_completed"
ACTION_MARKET_SESSION_OPEN = "market_session_open"
ACTION_MARKET_SESSION_CLOSE = "market_session_close"
ACTION_CANDLE_CLOSED = "candle_closed"
ACTION_BOT_ERROR = "bot_error"
ACTION_PIPELINE_SCHEDULED = "pipeline_scheduled"
ACTION_PIPELINE_FETCH_STARTED = "pipeline_fetch_started"
ACTION_PIPELINE_FETCH_COMPLETED = "pipeline_fetch_completed"
ACTION_PIPELINE_ANALYZE_STARTED = "pipeline_analyze_started"
ACTION_PIPELINE_ANALYZE_COMPLETED = "pipeline_analyze_completed"
ACTION_PIPELINE_BROKER_STARTED = "pipeline_broker_started"
ACTION_PIPELINE_BROKER_COMPLETED = "pipeline_broker_completed"
ACTION_PIPELINE_ASSOCIATE_STARTED = "pipeline_associate_started"
ACTION_PIPELINE_ASSOCIATE_COMPLETED = "pipeline_associate_completed"
ACTION_PIPELINE_FAILED = "pipeline_failed"
ACTION_PIPELINE_SKIPPED = "pipeline_skipped"
ACTION_ACCOUNT_SUMMARY_UPDATED = "account_summary_updated"
