#!/usr/bin/env bash
# Install host Caddy and write a TLS reverse-proxy Caddyfile for BrokerAI.
#
# Requires BROKERAI_DOMAIN (e.g. brokerai.example.com). Binds ACME on :80/:443
# and proxies to 127.0.0.1:${BROKERAI_WEB_PORT:-1989}.
#
# Optional BROKERAI_SUPABASE_DOMAIN adds a second site: Kong API on :8000 and
# Studio on :3000 (basic_auth from deploy/supabase/.env DASHBOARD_*).
#
# Usage (as root):
#   BROKERAI_DOMAIN=brokerai.example.com bash scripts/lib/install-caddy.sh
#   BROKERAI_DOMAIN=broker.example.com BROKERAI_SUPABASE_DOMAIN=supabase.example.com \
#     bash scripts/lib/install-caddy.sh
#
# Dry-run (no root / no systemd): write Caddyfile to BROKERAI_CADDYFILE only:
#   BROKERAI_CADDY_DRY_RUN=1 BROKERAI_CADDYFILE=/tmp/Caddyfile \
#     BROKERAI_DOMAIN=broker.example.com bash scripts/lib/install-caddy.sh
set -euo pipefail

DOMAIN="${BROKERAI_DOMAIN:-}"
SUPABASE_DOMAIN="${BROKERAI_SUPABASE_DOMAIN:-}"
WEB_PORT="${BROKERAI_WEB_PORT:-1989}"
KONG_PORT="${BROKERAI_SUPABASE_KONG_PORT:-8000}"
STUDIO_PORT="${BROKERAI_SUPABASE_STUDIO_PORT:-3000}"
INSTALL_DIR="${BROKERAI_INSTALL_DIR:-/opt/brokerai}"
CADDYFILE="${BROKERAI_CADDYFILE:-/etc/caddy/Caddyfile}"
SUPABASE_ENV="${BROKERAI_SUPABASE_ENV:-${INSTALL_DIR}/deploy/supabase/.env}"
DRY_RUN="${BROKERAI_CADDY_DRY_RUN:-0}"

_valid_hostname() {
  [[ "$1" =~ ^[A-Za-z0-9]([A-Za-z0-9.-]*[A-Za-z0-9])?$ ]] && [[ "$1" == *.* ]]
}

if [[ -z "${DOMAIN}" ]]; then
  echo "BROKERAI_DOMAIN is required (e.g. brokerai.example.com)" >&2
  exit 1
fi

if ! _valid_hostname "${DOMAIN}"; then
  echo "Invalid BROKERAI_DOMAIN: ${DOMAIN}" >&2
  exit 1
fi

if [[ -n "${SUPABASE_DOMAIN}" ]] && ! _valid_hostname "${SUPABASE_DOMAIN}"; then
  echo "Invalid BROKERAI_SUPABASE_DOMAIN: ${SUPABASE_DOMAIN}" >&2
  exit 1
fi

if [[ "${DRY_RUN}" != "1" && $EUID -ne 0 ]]; then
  echo "install-caddy.sh must be run as root (or set BROKERAI_CADDY_DRY_RUN=1)" >&2
  exit 1
fi

_env_get() {
  local file="$1" key="$2"
  [[ -f "${file}" ]] || return 0
  grep -E "^${key}=" "${file}" 2>/dev/null | head -1 | cut -d= -f2- || true
}

install_caddy_package() {
  if command -v caddy >/dev/null 2>&1; then
    return 0
  fi

  export DEBIAN_FRONTEND=noninteractive
  if apt-get install -y caddy 2>/dev/null; then
    return 0
  fi

  apt-get install -y debian-keyring debian-archive-keyring apt-transport-https curl gnupg
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' \
    | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' \
    | tee /etc/apt/sources.list.d/caddy-stable.list >/dev/null
  apt-get update -qq
  apt-get install -y caddy
}

hash_studio_password() {
  local password="$1"
  if command -v caddy >/dev/null 2>&1; then
    caddy hash-password --plaintext "${password}"
    return 0
  fi
  # Dry-run / CI without Caddy: bcrypt via Python (passlib or bcrypt if present).
  python3 - "${password}" <<'PY'
import sys
password = sys.argv[1]
try:
    import bcrypt
    print(bcrypt.hashpw(password.encode(), bcrypt.gensalt(rounds=14)).decode())
except Exception:
    # Placeholder accepted only for dry-run validation of Caddyfile structure.
    print("$2a$14$AAAAAAAAAAAAAAAAAAAAAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA")
PY
}

write_caddyfile() {
  local studio_user studio_pass studio_hash
  mkdir -p "$(dirname "${CADDYFILE}")"

  {
    cat <<EOF
# Generated by BrokerAI install-caddy.sh
# BrokerAI UI/API
${DOMAIN} {
	encode gzip

	reverse_proxy * 127.0.0.1:${WEB_PORT} {
		header_up X-Forwarded-Proto {scheme}
		header_up X-Forwarded-Host {host}
		header_up X-Real-IP {remote_host}
	}
}
EOF

    if [[ -n "${SUPABASE_DOMAIN}" ]]; then
      studio_user="$(_env_get "${SUPABASE_ENV}" DASHBOARD_USERNAME)"
      studio_pass="$(_env_get "${SUPABASE_ENV}" DASHBOARD_PASSWORD)"
      studio_user="${studio_user:-supabase}"
      if [[ -z "${studio_pass}" ]]; then
        echo "WARN: DASHBOARD_PASSWORD unset in ${SUPABASE_ENV}; using temporary password 'changeme'" >&2
        studio_pass="changeme"
      fi
      studio_hash="$(hash_studio_password "${studio_pass}")"

      cat <<EOF

# Supabase Kong (API) + Studio (basic_auth)
${SUPABASE_DOMAIN} {
	encode gzip

	@supabase_api path /auth/v1/* /rest/v1/* /graphql/v1 /realtime/v1/* /storage/v1/* /functions/v1/* /mcp /sso/*

	handle @supabase_api {
		reverse_proxy 127.0.0.1:${KONG_PORT} {
			header_up X-Forwarded-Proto {scheme}
			header_up X-Forwarded-Host {host}
			header_up X-Real-IP {remote_host}
		}
	}

	handle {
		basic_auth {
			${studio_user} ${studio_hash}
		}
		reverse_proxy 127.0.0.1:${STUDIO_PORT}
	}
}
EOF
    fi
  } >"${CADDYFILE}"

  chmod 644 "${CADDYFILE}"
}

if [[ "${DRY_RUN}" != "1" ]]; then
  install_caddy_package
fi

write_caddyfile

if [[ "${DRY_RUN}" != "1" ]]; then
  if command -v caddy >/dev/null 2>&1; then
    caddy validate --config "${CADDYFILE}" --adapter caddyfile >/dev/null
  fi
  systemctl enable caddy
  # Do not block forever on ACME when DNS is not ready yet.
  if ! timeout 60 systemctl start caddy; then
    echo "WARN: caddy start timed out (often DNS/ACME) — check: journalctl -u caddy -n 50" >&2
  fi
  timeout 15 systemctl reload caddy 2>/dev/null \
    || timeout 30 systemctl restart caddy 2>/dev/null \
    || true
fi

echo "Caddy TLS ready for https://${DOMAIN} → 127.0.0.1:${WEB_PORT}"
if [[ -n "${SUPABASE_DOMAIN}" ]]; then
  echo "Caddy TLS ready for https://${SUPABASE_DOMAIN} → Kong :${KONG_PORT} + Studio :${STUDIO_PORT} (basic_auth)"
fi
