#!/usr/bin/env bash
# Bootstrap self-hosted Supabase under deploy/supabase for BrokerAI.
#
# Usage:
#   ./scripts/setup-supabase.sh           # generate secrets + pull images
#   ./scripts/setup-supabase.sh --start   # also start the stack
#   ./scripts/setup-supabase.sh --stop
#   ./scripts/setup-supabase.sh --status
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SUPA="${ROOT}/deploy/supabase"
ENV_FILE="${ROOT}/.env"

ACTION="setup"
START=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --start) START=true; shift ;;
    --stop) ACTION="stop"; shift ;;
    --status) ACTION="status"; shift ;;
    -h | --help)
      sed -n '2,12p' "$0"
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      exit 1
      ;;
  esac
done

log() { echo "[supabase] $*"; }

require_docker() {
  if ! command -v docker >/dev/null 2>&1; then
    echo "Docker is required for self-hosted Supabase." >&2
    exit 1
  fi
  if ! docker info >/dev/null 2>&1; then
    echo "Docker is not running." >&2
    exit 1
  fi
}

compose() {
  (
    cd "${SUPA}"
    docker compose -f docker-compose.yml -f docker-compose.brokerai.yml "$@"
  )
}

ensure_env() {
  if [[ ! -f "${SUPA}/.env" ]]; then
    log "Creating ${SUPA}/.env from .env.example"
    cp "${SUPA}/.env.example" "${SUPA}/.env"
  fi

  # Default: loopback Kong/Studio. When BROKERAI_SUPABASE_DOMAIN is set (public
  # host Caddy), write HTTPS public URLs so GoTrue/Storage match the edge host.
  local public_url="http://127.0.0.1:8000"
  local site_url="http://127.0.0.1:5173"
  local proxy_domain="your-domain.example.com"
  local additional_redirects=""
  if [[ -n "${BROKERAI_SUPABASE_DOMAIN:-}" ]]; then
    public_url="https://${BROKERAI_SUPABASE_DOMAIN}"
    proxy_domain="${BROKERAI_SUPABASE_DOMAIN}"
    if [[ -n "${BROKERAI_DOMAIN:-}" ]]; then
      site_url="https://${BROKERAI_DOMAIN}"
      additional_redirects="https://${BROKERAI_DOMAIN}/**"
    fi
  fi

  PUBLIC_URL="${public_url}" SITE_URL_VAL="${site_url}" PROXY_DOMAIN_VAL="${proxy_domain}" \
  ADDITIONAL_REDIRECTS="${additional_redirects}" \
  python3 - "${SUPA}/.env" <<'PY'
import os
import sys
from pathlib import Path

p = Path(sys.argv[1])
replacements = {
    "SUPABASE_PUBLIC_URL": os.environ["PUBLIC_URL"],
    "API_EXTERNAL_URL": os.environ["PUBLIC_URL"],
    "SITE_URL": os.environ["SITE_URL_VAL"],
    "POSTGRES_HOST": "db",
    "POSTGRES_PORT": "5432",
    "KONG_HTTP_PORT": "8000",
    "STUDIO_PORT": "3000",
    "COMPOSE_FILE": "docker-compose.yml:docker-compose.brokerai.yml",
    "PROXY_DOMAIN": os.environ["PROXY_DOMAIN_VAL"],
}
extra = os.environ.get("ADDITIONAL_REDIRECTS", "").strip()
if extra:
    replacements["ADDITIONAL_REDIRECT_URLS"] = extra
lines = []
seen: set[str] = set()
for line in p.read_text().splitlines():
    if not line or line.lstrip().startswith("#") or "=" not in line:
        lines.append(line)
        continue
    key, _, _val = line.partition("=")
    key = key.strip()
    if key in replacements:
        lines.append(f"{key}={replacements[key]}")
        seen.add(key)
    else:
        lines.append(line)
for key, val in replacements.items():
    if key not in seen:
        lines.append(f"{key}={val}")
p.write_text("\n".join(lines) + "\n")
PY

  if ! grep -q '^JWT_SECRET=.\+' "${SUPA}/.env" 2>/dev/null \
    || grep -q 'your-super-secret\|CHANGE_ME\|replace-me' "${SUPA}/.env" 2>/dev/null; then
    log "Generating JWT and API keys"
    (cd "${SUPA}" && sh ./utils/generate-keys.sh --update-env >/dev/null)
  fi
}

write_brokerai_env_hints() {
  local anon service jwt pg_pass db_url supabase_url
  anon="$(grep -E '^ANON_KEY=' "${SUPA}/.env" | head -1 | cut -d= -f2- || true)"
  service="$(grep -E '^SERVICE_ROLE_KEY=' "${SUPA}/.env" | head -1 | cut -d= -f2- || true)"
  jwt="$(grep -E '^JWT_SECRET=' "${SUPA}/.env" | head -1 | cut -d= -f2- || true)"
  pg_pass="$(grep -E '^POSTGRES_PASSWORD=' "${SUPA}/.env" | head -1 | cut -d= -f2- || true)"
  db_url="postgresql+asyncpg://postgres:${pg_pass}@127.0.0.1:5432/postgres"
  supabase_url="http://127.0.0.1:8000"
  if [[ -n "${BROKERAI_SUPABASE_DOMAIN:-}" ]]; then
    supabase_url="https://${BROKERAI_SUPABASE_DOMAIN}"
  fi

  if [[ ! -f "${ENV_FILE}" ]]; then
    return 0
  fi

  if ! grep -q '^BROKERAI_DATABASE_URL=' "${ENV_FILE}" 2>/dev/null; then
    {
      echo ""
      echo "# Supabase / Postgres (generated by scripts/setup-supabase.sh)"
      echo "BROKERAI_DATABASE_URL=${db_url}"
      echo "BROKERAI_SUPABASE_URL=${supabase_url}"
      echo "BROKERAI_SUPABASE_ANON_KEY=${anon}"
      echo "BROKERAI_SUPABASE_SERVICE_ROLE_KEY=${service}"
      echo "BROKERAI_SUPABASE_JWT_SECRET=${jwt}"
    } >>"${ENV_FILE}"
    if [[ -n "${BROKERAI_SUPABASE_DOMAIN:-}" ]]; then
      echo "BROKERAI_SUPABASE_DOMAIN=${BROKERAI_SUPABASE_DOMAIN}" >>"${ENV_FILE}"
    fi
    log "Appended Supabase settings to ${ENV_FILE}"
  else
    log "BROKERAI_DATABASE_URL already set in ${ENV_FILE} — not overwriting"
  fi
}

case "${ACTION}" in
  stop)
    require_docker
    compose down
    log "Stopped"
    exit 0
    ;;
  status)
    require_docker
    compose ps
    exit 0
    ;;
esac

require_docker
ensure_env
write_brokerai_env_hints

log "Pulling Supabase images (multi-GB — progress below; 10–30+ minutes is normal)"
# Always show pull output (do not redirect). A silent pull looks like an installer hang.
if ! compose pull; then
  echo "docker compose pull failed" >&2
  exit 1
fi

if [[ "${START}" == "true" ]]; then
  log "Starting Supabase containers"
  compose up -d
  log "Waiting for Postgres (supabase-db)…"
  ready=0
  for _i in $(seq 1 90); do
    if docker exec supabase-db pg_isready -U postgres >/dev/null 2>&1; then
      ready=1
      break
    fi
    sleep 2
  done
  if [[ "${ready}" -ne 1 ]]; then
    echo "Postgres did not become ready within 180s — check: docker ps -a" >&2
    compose ps || true
    exit 1
  fi
  log "Postgres is ready"
  if [[ -n "${BROKERAI_SUPABASE_DOMAIN:-}" ]]; then
    log "Public API (via host Caddy): https://${BROKERAI_SUPABASE_DOMAIN}"
    log "Loopback: Studio http://127.0.0.1:3000  Kong http://127.0.0.1:8000  Postgres 127.0.0.1:5432"
  else
    log "Studio: http://127.0.0.1:3000  API: http://127.0.0.1:8000  Postgres: 127.0.0.1:5432"
  fi
fi

log "Setup complete"
